language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1
  - nightly

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email: false

codecov: true

jobs:
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      arch: x64
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      name: "HTML"
      after_success: skip
  exclude:
  - os: osx
    arch: x86
