# This file is machine-generated - editing it directly is not advised

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[JuliaInterpreter]]
deps = ["InteractiveUtils"]
git-tree-sha1 = "26232b43c5445182a1acbd13258bfbd5be5a1dae"
repo-rev = "master"
repo-url = "https://github.com/JuliaDebug/JuliaInterpreter.jl.git"
uuid = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
version = "0.1.1"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"
